### ISSUE TITLE
Not prefectly ajusted

### ISSUE THREAD

**Issue by jgarces02** [SWolf23/rstudio-darkTheme#1]
Thanks for share these files, it works without problems! But I think that a clear and thick line separating panels could be a great advance (I would do it, but I'm a bit lost with code yet). Thanks!

**Comment by SWolf23** [comment]
Yeah thx for the report. The problems is in my solution as it more sprays over the finished paintings than change the colors from the beginning. Anyway a dark theme is now in rstudio so i drop the project. Maybe in the future i will try to make another theme, that than has a completly different solution but for the moment i don't have the time nor a solution for the problem.
Thx for your interest
