### ISSUE TITLE
Topmost bar

### ISSUE THREAD

**Issue by juanpide** [SWolf23/rstudio-darkTheme#2]
We need also to change the topmost bar, the bar with "RStudio, Edit, Code, ..." that remains grey.

**Comment by SWolf23** [comment]
Yeah thx for the report. The problems is in my solution as it more sprays over the finished paintings than change the colors from the beginning. Anyway a dark theme is now in rstudio so i drop the project. Maybe in the future i will try to make another theme, that than has a completly different solution but for the moment i don't have the time nor a solution for the problem.
Thx for your interest
