### ISSUE TITLE
# panel ribbon when minimized 

### ISSUE THREAD

**Issue by lyzerana** [SWolf23/rstudio-darkTheme#3]
much appreciated tweaks!
possible improvements: 
- panel ribbon when minimized default to white, would be great to also get them dark.
- symbols and radio buttons (e.g. under Packages) could do with a bit of a darker background; especially on smaller screens those are lightening up and distract

**Comment by SWolf23** [comment]
Yeah thx for the report. The problems is in my solution as it more sprays over the finished paintings than change the colors from the beginning. Anyway a dark theme is now in rstudio so i drop the project. Maybe in the future i will try to make another theme, that than has a completly different solution but for the moment i don't have the time nor a solution for the problem.
Thx for your interest
