### ISSUE TITLE
View() + show in new window bugged

### ISSUE THREAD

**Issue by ghost** [SWolf23/rstudio-darkTheme#4]
If you want to view a dataframe with View() and pop the window out the window will stay blank white and cannot be closed. 
If you do the same again, another window will appear, which seems to work, but the head line, where you can filter or  pop the window back into RStudio,  is weirdly formatted.

**Comment by philiporlando** [comment]
In addition to this View() bug, right-clicking on a dataframe and selecting "Reload" will cause the entire window to go blank. Right-clicking a second time and selecting "Stop" will bring things back to normal. 
However, this only seems to occur when right-clicking on dataframes, and not R scripts.

**Comment by SWolf23** [comment]
Yeah thx for the report. The problems is in my solution as it more sprays over the finished paintings than change the colors from the beginning. Anyway a dark theme is now in rstudio so i drop the project. Maybe in the future i will try to make another theme, that than has a completly different solution but for the moment i don't have the time nor a solution for the problem.
Thx for your interest
