### ISSUE TITLE
script panel issue

### ISSUE THREAD

**Issue by SebastianSosa** [SWolf23/rstudio-darkTheme#5]
The theme is very beautiful but if we detach the script panel, it’s impossible to use it…
And if the user can have the possibility to choose the theme of the script panel it will be perfect.

Anyway, great job !

**Comment by SWolf23** [comment]
Yeah thx i know. The problems is in my solution as it more sprays over the finished painting than change the colors from the beginning. Anyway a dark theme is now in rstudio so i drop the project maybe in the future i will try to make another theme that than has a completly different solution but for the moment i don't have the time.
Thx for your interest
